import { StyleSheet } from 'react-native';

export const st = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center' },
  abs: { position: 'absolute' },
  h1: { color: '#fff', fontSize: 34, fontWeight: '700', textAlign: 'center', marginTop: 22, lineHeight: 40 },
  sub: { color: '#fff', textAlign: 'center', fontSize: 15, marginTop: 8, marginBottom: 22 },
  lab: { color: '#fff', fontSize: 13, letterSpacing: 1, marginLeft: 8, marginBottom: 5 },
  pill: { backgroundColor: '#fff', borderRadius: 30, height: 56, paddingHorizontal: 22, fontSize: 16 },
  eye: { position: 'absolute', right: 18, top: 16 },
  btn: { borderRadius: 30, paddingVertical: 16, alignItems: 'center', marginTop: 6 },
  bt1: { color: '#fff', fontWeight: '700', fontSize: 20 },
  lk: { color: '#fff', textAlign: 'center', marginTop: 14, fontSize: 15 },
  u: { textDecorationLine: 'underline' },
  pw: { position: 'absolute', left: 14, bottom: 8, color: '#222', fontSize: 11, fontWeight: '700' },
  cap: { backgroundColor: '#000', color: '#fff', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, fontSize: 18, overflow: 'hidden' },
  alt: { flex: 1, backgroundColor: '#fff', borderRadius: 30, paddingVertical: 14, alignItems: 'center' },
  altT: { fontWeight: '700', fontSize: 12 },
  search: { flex: 1, backgroundColor: '#fff', borderRadius: 14, padding: 14, marginHorizontal: 10, elevation: 2 },
  bell: { backgroundColor: '#1fbfa5', width: 52, height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  save: { textAlign: 'right', color: '#999', fontWeight: '700', fontSize: 15, marginVertical: 14 },
  ulab: { fontWeight: '700', fontSize: 16, marginTop: 10 },
  ul: { borderBottomWidth: 2, borderBottomColor: '#111', height: 40, fontSize: 15 },
  sec: { fontWeight: '800', fontSize: 17, marginTop: 24, marginBottom: 12 },
  dir: { borderWidth: 2, borderColor: '#bbb', borderRadius: 26, paddingVertical: 12, paddingHorizontal: 22, marginBottom: 12 },
  dirT: { fontSize: 14, textTransform: 'uppercase' },
  rest: { fontWeight: '900', fontSize: 20, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8 },
  cup: { flex: 1, borderWidth: 2, borderColor: '#bbb', borderRadius: 18, padding: 8, marginRight: 6, minHeight: 80, justifyContent: 'center' },
  cupT: { fontSize: 10, textAlign: 'center' },
  bnav: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 70, backgroundColor: 'rgba(255,255,255,0.92)', flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' },
  bt: { fontSize: 15, color: '#111' },
  eh: { color: '#111', fontWeight: '800', fontSize: 18, marginTop: 34, marginBottom: 18 },
  ep: { fontSize: 16, marginBottom: 18, color: '#111' },
  dot: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginLeft: 40 },
  pt: { fontSize: 17, color: '#111' },
  line: { position: 'absolute', left: 56, top: 38, width: 4, height: 58, backgroundColor: '#111' },
  rt: { textAlign: 'center', fontSize: 22, fontWeight: '800', marginVertical: 14 },
  map: { height: 150, backgroundColor: '#d6d2cd', borderTopLeftRadius: 14, borderTopRightRadius: 14, overflow: 'hidden' },
  mapF: { backgroundColor: '#fff', padding: 8, borderBottomLeftRadius: 14, borderBottomRightRadius: 14 },
  mapB: { backgroundColor: '#e26b6b', color: '#fff', fontSize: 11, paddingHorizontal: 18, paddingVertical: 6, borderRadius: 20, overflow: 'hidden' },
  grid: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 30 },
  tile: { backgroundColor: '#fff', borderRadius: 18, minHeight: 118, alignItems: 'center', justifyContent: 'center', padding: 8 },
  te: { fontSize: 40 },
  tt: { fontWeight: '800', fontSize: 12, textAlign: 'center', marginTop: 4 },
  cancel: { backgroundColor: '#f22d2d', borderRadius: 12, alignItems: 'center', paddingVertical: 14, marginTop: 20 },
});
